<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class VendorSeeder extends Seeder
{
    public function run(): void
    {
        $vendors = [
            '126 Chinese',
            '24 Hr Car Wash',
            '241 Pizza',
            '7-Eleven',
            'A&W',
            'A30 Express',
            'Abbotsford Taxi',
            'Access Cash',
            'Air A Fare Food',
            'Air Canada',
            'Air- Serv',
            'Aircab Inc',
            'Allied Black',
            'Amazon',
            'Anderson Avenue',
            'Aramark',
            "Arby's",
            'Arnprior Motor Inn',
            'Asian Cuisine',
            'Atlantis Limousine',
            'ATM',
            'Avis Car Rental',
            'Bank Of Montreal',
            "Barney's Motel",
            'Basics',
            'BC Ferries',
            'BCMInns',
            'Bedrock Bistro',
            'BG Fuels',
            'Birchville Motel',
            'Boston Pizza',
            'Bram City Taxi',
            'Bulk Barn',
            'Burger King',
            'Canada Post',
            'Canadian Tire',
            'Capital Cab',
            'Capitol Taxi',
            'Captain Taxi',
            'Cardtronic',
            'Carolyn Beach Inn',
            'Charlie Lake Store',
            'Checker Cab',
            "Ches's Fish & Chips",
            'Chevron',
            "China Liang's Buffett",
            'China Taste',
            'City Cabs',
            'City Wide Taxi',
            'Cobequid Pass',
            'Comfort Inn',
            'Comox Taxi',
            'Confederation Bridge',
            'Continental Motel',
            "Cooney's Cab",
            'Co-Op',
            'Co-Op Taxi Line',
            'Costco',
            'Couche-Tard',
            'Country Squire Motel',
            "Cristy's Rotisserie Chicken",
            'Dauw Auto Wash',
            'Days Inn',
            'DC Bank',
            'Deep River Motel',
            "Denny's",
            'Dollarama',
            "Domino's Pizza",
            'Ebus',
            'Elegant Limousine',
            'English River Inn',
            'Enterprise Car Rental',
            'Esso',
            'Factory Direct',
            'Fas Gas',
            'Fens',
            'Firehouse Subs',
            'Flair Airlines',
            'Flight Stop',
            'Flying J',
            'Food Basics',
            'Food Mart',
            'Foodland',
            'Freshco',
            'Frisco ATMS',
            'Gao Chinese',
            'Ginkgo',
            'GO Transit',
            'Gold Car Wash',
            'Grand River Transit',
            'Great Buffet of China',
            'Greater Edmonton Taxi',
            'Greco Pizza',
            'Green Taxi',
            'Happy Goose Car Wash',
            "Harvey's",
            'Hide Away Inn',
            'High Falls Inn',
            'Holiday Inn',
            'Holiday Motel',
            'Hotels.com',
            "Humpty's",
            'Husky',
            'Irving',
            'J&A Convenience',
            'Jiffy Lube',
            'Kamloops Carwash Ltd',
            'Kelowna Cabs',
            'Kelowna Eco Taxi',
            'Kelseys',
            "Kent's Towing",
            'KFC',
            'Kings Buffet',
            'Koodo',
            'Kv Cab',
            'La Roma Motel',
            'Limocar',
            'Linn Chau',
            'Little Caesars',
            'London Taxi',
            'M&M Food Market',
            'MacEwen',
            "MacLure's Cab",
            "Mac's",
            'Manchu Wok',
            'Manulife',
            "Marie's Mini Mart",
            'Marine Atlantic',
            'Maritime Bus',
            'Mary Browns',
            'McDonalds',
            'Metro',
            'Motel 6',
            'Mountain View Hope',
            'Mr. Lube',
            'Mr. Sub',
            "Nando's",
            'Newfoundland Cabs',
            'Nights Inn Motel',
            'North Hotel Two',
            'Nova Scotia Parks',
            'ONroute',
            'Ontario Parks',
            'Orangestore',
            'Pacific Cabs',
            'Panago',
            'Park2Go',
            'Parks NB',
            'Pearson Airport',
            'Pelletiers',
            'Petro-Canada',
            'Pinks Burger',
            'Pioneer',
            'Pizza Hut',
            'Popeyes',
            'Porter Airlines',
            'Quality Hotel',
            'Quality Inn',
            'Ramada Inn',
            'Red Arrow',
            'Red Dog Inn',
            "Robin's Donut",
            'Royal Bank of Canada',
            'Scotiabank',
            'Shehanai',
            'Shell',
            'Shoppers Drug Mart',
            'Siriusxm.Ca',
            'Skipthedishes',
            'Sky View Motel',
            'SkyShuttle',
            'Splash to Sparkle',
            'Square.ca',
            'Star Lodge',
            'St-Hubert Bbq',
            'Strathmore Auto Spa',
            'Strykerz',
            'Subway',
            'Sun Taxi',
            'Sunset Grill',
            'Super 8',
            'Swiss Chalet',
            'Taco Bell',
            'Taste of Philly',
            'Taxi',
            'Terra Nova NP',
            'The China Gardens',
            'The Cliffe',
            'The Works',
            'Thriftlodge',
            'Tim Hortons',
            'Timberland Motel',
            'Town & Country Motel',
            'Trailside Gas',
            'Travelodge',
            'Uber',
            'Uber Eats',
            'Ultramar',
            'U-Need-A-Cab',
            'Uniglass',
            'United Taxi',
            'UP Express',
            'uShip.com',
            'Vedder River Inn',
            'Via Rail',
            'W.O Stinson & Son',
            'Wal-Mart',
            'Wash World',
            'Waterloo Taxi',
            "Wendy's",
            'WestJet',
            'White Cab Co Ltd',
            'White Otter Inn',
            'Whitespot',
            'Widus Inn',
            'Woodward',
            'Yellow Cab',
            'yyc',
            'Zoom Car Rental',
        ];

        foreach ($vendors as $index => $vendor) {
            DB::table('vendors')->insertOrIgnore([
                'name'       => $vendor,
                'slug'       => Str::slug($vendor),
                'is_active'  => true,
                'sort_order' => ($index + 1) * 10,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}